// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTMTMjrP0whC45woXfR7_2y8f7l1kVgPA',
    appId: '1:828029880794:web:d491b5343fc03a25af58e3',
    messagingSenderId: '828029880794',
    projectId: 'cricbit-a96eb',
    authDomain: 'cricbit-a96eb.firebaseapp.com',
    storageBucket: 'cricbit-a96eb.appspot.com',
    measurementId: 'G-FVQ3JNZ989',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6eEfeVtM4fEX-6z7nArfPp6kstezyuI',
    appId: '1:828029880794:android:c726bd1dcfd4491aaf58e3',
    messagingSenderId: '828029880794',
    projectId: 'cricbit-a96eb',
    storageBucket: 'cricbit-a96eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38conchEZhnYGFv1bpW4a8-bT0eHSghA',
    appId: '1:828029880794:ios:8d5bf6e4f18b85ccaf58e3',
    messagingSenderId: '828029880794',
    projectId: 'cricbit-a96eb',
    storageBucket: 'cricbit-a96eb.appspot.com',
    iosClientId: '828029880794-vh48lctj7ucfvcahqe3rnra4ta2vs71n.apps.googleusercontent.com',
    iosBundleId: 'com.example.liver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC38conchEZhnYGFv1bpW4a8-bT0eHSghA',
    appId: '1:828029880794:ios:e65f08af227745f1af58e3',
    messagingSenderId: '828029880794',
    projectId: 'cricbit-a96eb',
    storageBucket: 'cricbit-a96eb.appspot.com',
    iosClientId: '828029880794-rek3vfibhkml1is3lgnvgjg9bhu003mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.liver.RunnerTests',
  );
}
